db:
    image: mysql:5.7
    ports:
        - 3307:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: tiller-data
        MYSQL_USER: tiller-data
        MYSQL_PASSWORD: tiller-data
    volumes:
        - mysql-data:/var/lib/mysql
python:
    build: ./
    ports:
        - 5000:5000
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: tiller-data
        MYSQL_USER: tiller-data
        MYSQL_PASSWORD: tiller-data
        AMAZON_S3_DATALAKE: "s3://datalake-tiller.amazon.com"
    volumes:
        - ./:/app
    links:
        - db
