db:
    image: mysql:5.7
    ports:
        - 3307:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: tillerinterview
        MYSQL_USER: tillerinterview
        MYSQL_PASSWORD: tillerinterview
    volumes:
        - mysql-data:/var/lib/mysql
python:
    build: ./
    ports:
        - 5000:5000
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: tillerinterview
        MYSQL_USER: tillerinterview
        MYSQL_PASSWORD: tillerinterview
        AMAZON_S3_DATALAKE: "https://s3-eu-west-1.amazonaws.com/tillerinterview/hamonromain20180511/"
    volumes:
        - ./:/app
    links:
        - db
